import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Design System: Material You palette
        "on-primary": "#faf6ff",
        "primary-fixed": "#e2dfff",
        "on-surface": "#2a3439",
        "primary-dim": "#4034d7",
        "on-primary-container": "#3f33d6",
        "surface-bright": "#f7f9fb",
        "secondary-container": "#d3e4fe",
        "secondary-fixed-dim": "#c5d6f0",
        "inverse-on-surface": "#9a9d9f",
        "surface-dim": "#cfdce3",
        "surface-container-high": "#e1e9ee",
        "surface-container": "#e8eff3",
        "surface-container-low": "#f0f4f7",
        "outline-variant": "#a9b4b9",
        "tertiary-dim": "#4b526c",
        "surface-container-highest": "#d9e4ea",
        "tertiary-fixed": "#d2d9f8",
        "secondary-dim": "#44546a",
        "tertiary": "#575e78",
        "tertiary-fixed-dim": "#c4cbe9",
        "on-secondary-fixed-variant": "#4d5d73",
        "on-tertiary-fixed": "#323951",
        "primary-container": "#e2dfff",
        "primary-fixed-dim": "#d2d0ff",
        "on-tertiary-container": "#444c65",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#314055",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#435368",
        "on-secondary": "#f7f9ff",
        "on-primary-fixed-variant": "#4a40e0",
        "surface-variant": "#d9e4ea",
        "on-primary-fixed": "#2a13c5",
        "on-error": "#fff7f7",
        "outline": "#717c82",
        "inverse-primary": "#8582ff",
        "inverse-surface": "#0b0f10",
        "secondary": "#506076",
        "error-container": "#ff8b9a",
        "secondary-fixed": "#d3e4fe",
        "error-dim": "#4f0116",
        "primary": "#4d44e3",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#4e556f",
        "on-tertiary": "#faf8ff",
        "surface-tint": "#4d44e3",
        "on-background": "#2a3439",
        "tertiary-container": "#d2d9f8",
        "on-error-container": "#782232",
        "on-surface-variant": "#566166",
        "error": "#9e3f4e",
        // Legacy palette kept for backwards compatibility
        shell: "#f8f9fc",
        ink: "#1a1a1a",
        moss: "#16a34a",
        clay: "#ea580c",
        pine: "#0f766e",
        "primary-600": "#4d44e3",
        "primary-700": "#4034d7",
        "primary-500": "#6b63e8",
        "primary-400": "#8a84ee",
        "accent-purple": "#a855f7",
        "accent-pink": "#ec4899",
        "accent-orange": "#f97316",
        "accent-emerald": "#10b981",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        xxl: "1.5rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      boxShadow: {
        card: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        "card-hover": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
        soft: "0 2px 8px rgba(0, 0, 0, 0.08)",
        glow: "0 0 20px rgba(77, 68, 227, 0.15)",
      },
      keyframes: {
        rise: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideIn: {
          "0%": { opacity: "0", transform: "translateX(-10px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        rise: "rise 420ms ease-out both",
        fadeIn: "fadeIn 300ms ease-in-out",
        slideIn: "slideIn 350ms ease-out",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
